namespace Chapter13_ExceptionHandling.Exc;

/* An exception can be generated by one
method and caught by another. */

public class ExcDemo
{
    public static void test() {
        try {
            ExcTest.GenException();
        }
        catch (IndexOutOfRangeException) {
            // Catch the exception.
            Console.WriteLine("Index out-of-bounds!");
        }
        Console.WriteLine("After catch block.");
    }
}